nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: []
            allow_headers: []
            allow_methods: []
            expose_headers: []
            max_age: 0
            hosts: []
            origin_regex: false
            forced_allow_origin_value: ~
        paths:
            '^/':
                allow_origin: ['http://brokentime-project.surge.sh/']
                allow_headers: ['content-type', 'application/json']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600