vich_uploader:
    db_driver: orm

    mappings:
        user_images:
            uri_prefix: /pictures/user
            upload_destination: '%kernel.project_dir%/public/pictures/user'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        fiction_images:
            uri_prefix: /pictures/fiction
            upload_destination: '%kernel.project_dir%/public/pictures/fiction'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
